var diagrammesDefaut = [
  {
    id: 1700000000010,
    titre: "Architecture example",
    shapes: [
      {
        id: "s1",
        type: "rounded",
        x: 78,
        y: 131,
        w: 130,
        h: 50,
        text: "Client Web",
        color: "t-sky",
      },
      {
        id: "s2",
        type: "rect",
        x: 281,
        y: 134,
        w: 130,
        h: 50,
        text: "API Gateway",
        color: "t-green",
      },
      {
        id: "s3",
        type: "rect",
        x: 506,
        y: 38,
        w: 130,
        h: 50,
        text: "Auth Service",
        color: "t-violet",
      },
      {
        id: "s4",
        type: "rect",
        x: 505,
        y: 197,
        w: 130,
        h: 50,
        text: "Data Service",
        color: "t-amber",
      },
      {
        id: "s5",
        type: "db",
        x: 771,
        y: 223,
        w: 100,
        h: 65,
        text: "PostgreSQL",
        color: "t-rose",
      },
      {
        id: "s6",
        type: "cloud",
        x: 725,
        y: -4,
        w: 110,
        h: 65,
        text: "OAuth 2.0",
        color: "t-teal",
      },
    ],
    arrows: [
      {
        id: "a1",
        from: "s1",
        to: "s2",
        label: "HTTPS",
      },
      {
        id: "a2",
        from: "s2",
        to: "s3",
        label: "",
      },
      {
        id: "a3",
        from: "s2",
        to: "s4",
        label: "",
      },
      {
        id: "a4",
        from: "s4",
        to: "s5",
        label: "SQL",
      },
      {
        id: "a5",
        from: "s3",
        to: "s6",
        label: "",
      },
    ],
  },
  {
    id: 1774104617783,
    titre: "Nouveau diagramme",
    shapes: [],
    arrows: [],
  },
];
